core/urls.py
from django.contrib.staticfiles.views import serve
from django.urls import path, re_path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('shop/<str:ctg>/<str:ctg2>', shop, name='shop'),
    path('sales', new_items, name='new_items'),
    path('cart', cart, name='cart'),
    path('detail/<slug>', detail, name='detail'),
    path('add-to-cart1', add_to_cart1, name='add-to-cart1'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('profile', profile, name='profile'),
    path('about_us', about_us, name='about_us'),
    path('delete_duplicates', delete_duplicates, name='delete_duplicates'),
    path('slug', slug, name='slug'),
]

templates/cart.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Alta Stroy</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css'%}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css'%}">

    <link rel="stylesheet" href="{% static 'css/aos.css'%}">

    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
    <link rel="stylesheet" href="{% static 'css/style2.css'%}">

  </head>
  <body>

  <div class="site-wrap">
    {% include 'header.html' %}

    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0"><a href="{% url 'core:home' %}">Главная</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Корзина</strong></div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row mb-5">
          <form class="col-md-12" method="post">
            <div class="site-blocks-table">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th class="product-thumbnail">Фотография</th>
                    <th class="product-name">Название</th>
                    <th class="product-price">Цена</th>
                    <th class="product-quantity">Количество</th>
                    <th class="product-total">Сумма</th>
                    <th class="product-remove">Удалить</th>
                  </tr>
                </thead>
                <tbody>
                {% for item in order.items.all %}
                  <tr>
                    <td class="product-thumbnail">
                      <img src="{{ item.item.image.url }}" alt="Image" class="img-fluid">
                    </td>
                    <td class="product-name">
                      <h2 class="h5 text-black">{{ item.item.title }}</h2>
                    </td>
                    <td>{{ item.item.get_price }}</td>
                    <td>
                      <div class="input-group mb-3" style="max-width: 120px;">
                        <div class="input-group-prepend">
                          <a href="{% url 'core:remove-single-item-from-cart' item.item.slug %}" class="btn btn-outline-primary">&minus;</a>
                        </div>
                          <p class="form-control text-center">{{ item.quantity }}</p>
                        <div class="input-group-append">
                          <a href="{% url 'core:add-to-cart' item.item.slug %}" class="btn btn-outline-primary" >&plus;</a>
                        </div>
                      </div>

                    </td>
                    <td>{{ item.get_total_item_price }}</td>
                    <td><a href="{% url 'core:remove-from-cart' item.item.slug %}" class="btn btn-primary btn-sm">X</a></td>
                  </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </form>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="row mb-5">
              <div class="col-md-6 mb-3 mb-md-0">
                <button class="btn btn-primary btn-sm btn-block">Очистить корзину</button>
              </div>
              <div class="col-md-6">
                <button class="btn btn-outline-primary btn-sm btn-block">Продолжить покупки</button>
              </div>
            </div>
          </div>
          <div class="col-md-6 pl-5">
            <div class="row justify-content-end">
              <div class="col-md-7">
                <div class="row">
                  <div class="col-md-12 text-right border-bottom mb-5">
                    <h3 class="text-black h4 text-uppercase">Общая сумма</h3>
                  </div>
                </div>
                <div class="row mb-5">
                  <div class="col-md-6">
                    <span class="text-black">Итог</span>
                  </div>
                  <div class="col-md-6 text-right">
                    <strong class="text-black">$230.00</strong>
                  </div>
                </div>

                <div class="row">
                  <div class="col-md-12">
                    <button class="btn btn-primary btn-lg py-3 btn-block" onclick="window.location='checkout.html'">Отправить заявку</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% include 'footer.html' %}
  </div>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js'%}"></script>
  <script src="{% static 'js/popper.min.js'%}"></script>
  <script src="{% static 'js/bootstrap.min.js'%}"></script>
  <script src="{% static 'js/owl.carousel.min.js'%}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
  <script src="{% static 'js/aos.js'%}"></script>

  <script src="{% static 'js/main.js'%}"></script>

  </body>
</html>

templates/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
<title>Alta Stroy</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css'%}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css'%}">

    <link rel="stylesheet" href="{% static 'css/aos.css'%}">

    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
  <link rel="stylesheet" href="{% static 'css/style2.css'%}">

  </head>
  <style>
      *{
        font-family: 'Montserrat', sans-serif;
      }
  </style>
  <body>

  <div class="site-wrap">
    {% include 'header.html' %}
    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0"><a href="{% url 'core:home' %}">Главная</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">{{ item.category.title }}</strong>  /  </span> <strong class="text-black">{{ item.subcategory.title }}</strong>  /  </span> <strong class="text-black">{{ item.title }}</strong></div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <img src="{{ item.image.url }}" alt="Image" class="img-fluid">
          </div>
          <div class="col-md-6">
            <h2 class="text-black">{{ item.title }}</h2>
            <p><strong class="text-primary h4">{{ item.get_price }}₸</strong></p>
            <p>Артикул: {{ item.articul }}</p>
              <p>Бренд: {{ item.brand }}</p>
              <p>Диаметр: {{ item.diameter }}</p>
              <p>Длинна: {{ item.length }}</p>
              <p>Ширина: {{ item.width }}</p>
              <p>Высота: {{ item.height }}</p>
            <div class="mb-5">
              <div class="input-group mb-3" style="max-width: 120px;">
              <div class="input-group-prepend">
                <button class="btn btn-outline-primary js-btn-minus" type="button">&minus;</button>
              </div>
              <input type="text" class="form-control text-center" value="1" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
              <div class="input-group-append">
                <button class="btn btn-outline-primary js-btn-plus" type="button">&plus;</button>
              </div>
            </div>

            </div>
          <p><button class="buy-now btn btn-sm btn-primary" id="add_to_card"  value="{{ item.slug }}" type="button" name="{{ item.title }}">В Корзину</button></p>


          </div>
        </div>
      </div>
    </div>
  <hr>
  <div class="row d-flex justify-content-between" style="margin-left: 10%; margin-right: 10%">
      <div style="margin-bottom: 50px">
      <h2 style="color: black;">Внешность:</h2>
          {% for text in description2 %}
              <p>{{ text }}</p>
          {% endfor %}
      </div>

      <div style="margin-bottom: 50px">
        <h2 style="color: black">Тех описание:</h2>
          {% for text in description1 %}
                  <p>{{ text }}</p>
              {% endfor %}
      </div>
  </div>

    {% include 'footer.html' %}
  </div>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js'%}"></script>
  <script src="{% static 'js/popper.min.js'%}"></script>
  <script src="{% static 'js/bootstrap.min.js'%}"></script>
  <script src="{% static 'js/owl.carousel.min.js'%}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
  <script src="{% static 'js/aos.js'%}"></script>
  <script src="{% static 'js/main.js'%}"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css">
  <script type="text/javascript">
    const buttons = document.querySelectorAll('button[id="add_to_card"]');
    console.log(buttons)
    for(let i = 0; i < buttons.length ; i++) {
        if(buttons[i].id == 'add_to_card'){
            console.log(buttons[i]['value'])
            buttons[i].addEventListener('click',function(e){
                e.preventDefault();
                $.ajax({
                    type:'POST',
                    url:'{% url "core:add-to-cart1" %}',
                    data:
                    {
                        slug:buttons[i]['value'],
                        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                    },
                    dataType:'json',
                    success:function(){
                        let p = document.getElementById('number');
                        console.log(p)
                        alert("Добавлено в корзину " + buttons[i]['name']);
                    }
                })
            });
        }
    }
</script>

  </body>
</html>

templates/h.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<title>Alta Stroy</title>
</head>
<body>
    <input placeholder="Enter number" id="input">
    <button onclick="func()">click</button>
    <input id="input2" >
</body>
<script>
    function func(){
        document.getElementById('input2').disabled = true
    }
</script>
</html>

templates/header.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css"%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css'%}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css'%}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css'%}">


    <link rel="stylesheet" href="{% static 'css/aos.css'%}">

    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
    <style>
        html { scroll-behavior: smooth;

        }
        *{
            padding: 0;
            margin: 0;
            color: black;
        }
    </style>
</head>
<header class="site-navbar" role="banner">
      <div class="site-navbar-top">
        <div style="margin: 0 7%;">
          <div class="row align-items-center p-0 m-0">

            <div class="col-6 col-md-4 order-2 order-md-1 site-search-icon text-left">
              <form action="" class="site-block-top-search">
                <span class="icon icon-search2"></span>
                <input type="text" class="form-control border-0" name="articul" placeholder="Найти">
              </form>
            </div>

            <div class="col-12 mb-3 mb-md-0 col-md-4 order-1 order-md-2 text-center">
              <div style="display: flex; flex-direction: column; height: 120px">
                <a href="{% url 'core:home' %}" style="height: 80px"><img src="{% static 'img/logo.jpg' %}" height="120px" style="height: 120px"></a>
              </div>
            </div>

            <div class="col-6 col-md-4 order-3 order-md-3 text-right">
              <div class="site-top-icons d-flex justify-content-end text-right" style="gap: 5px;">
                <ul>
                  <li><a href="{% url 'core:profile' %}"><span class="icon icon-person"></span></a></li>
                  <li>
                    <a href="{% url 'core:cart' %}" class="site-cart">
                      <span class="icon icon-shopping_cart"></span>
                    </a>
                  </li>
{#                  <li class="d-inline-block d-md-none ml-md-0"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu"></span></a></li>#}
                </ul>
              </div>
            </div>

          </div>
        </div>
      </div>
      <nav class="site-navigation text-right text-md-center w-100" role="navigation">
        <div style="padding: 0">
          <ul class="site-menu js-clone-nav d-none d-md-block">
              {% for category in categories %}
            <li class="has-children">
              <a style="color: black; font-size: 75%">{{ category.title }}</a>
              <ul class="dropdown">
                  {% for sub in category.subcategories.all %}
                    <li><a href="{% url 'core:shop' 'Cплитерные блоки' 'Сплитерный блок «фаска»' %}">{{ sub.title }}</a></li>
                  {% endfor %}
              </ul>
            </li>
              {% endfor %}
          </ul>
        </div>
      </nav>
    </header>
</html>

templates/parket.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
<title>Alta Stroy</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
</head>
<body>
{% include 'header.html' %}
    <h1 class="mb-3 text-dark">Паркет</h1>
    {% for sub in subcategories %}
        <div class="mb-3" style="background: url({{ sub.image.url }}); background-size: cover; position: relative; height: 500px; text-align: center; width: 75%">
            <h1 style="color: white; height: 100%; position: absolute; top: 40%; left: 20%">{{ sub.title }}</h1>
        </div>
    {% endfor %}

{% include 'footer.html' %}
</body>
</html>

templates/shop.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
  <head>
<title>Alta Stroy</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css'%}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/aos.css'%}">
    <link rel="stylesheet" href="{% static 'css/style1.css'%}">
  <link rel="stylesheet" href="{% static 'css/style2.css'%}">

  </head>
  <body>

  <div class="site-wrap">
    {% include 'header.html'  %}

    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0"><a href="{% url 'core:home' %}">Главная</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">{{ category.title }}</strong></span> <strong class="text-black">/{{ subcategory.title }}</strong></div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row mb-5">

          <div class="col-md-9 order-2">

            <div class="row">
              <div class="col-md-12 mb-5">
                <div class="float-md-left mb-4"><h2 class="text-black h5">Все товары</h2></div>
              </div>
            </div>
            <div class="row mb-5">
            {% for item in items %}
              <div class="col-sm-6 col-lg-4 mb-4" data-aos="fade-up">
                <div class="block-4 text-center border">
                  <figure class="block-4-image">
                    <a href="{% url 'core:detail' item.slug %}"><img src="{{ item.image.url }}" alt="Image placeholder" class="img-fluid" style="height: 250px"></a>
                  </figure>
                  <div class="block-4-text p-4" style="color: black">
                    <h3><a class="text-dark" href="{% url 'core:detail' item.slug %}" style="font-size: 80%">{{ item.title }}</a></h3>
                      <p class="font-weight-bold text-dark" style="font-size: 120%; font-weight: bold; color: black">₸{{ item.get_price }}</p>
                  </div>
                    <p><button class="buy-now btn btn-sm btn-primary" id="add_to_card"  value="{{ item.slug }}" type="button" name="{{ item.title }}">В Корзину</button></p>

                </div>
              </div>
              {% endfor %}
            </div>
{#          {% endif %}#}
{#            {% if items.has_other_pages %}#}
{#              <nav class="d-flex justify-content-center wow fadeIn">#}
{#                <ul class="pagination pg-blue">#}
{#                  {% if items.has_previous %}#}
{#                  <li class="page-item">#}
{##}
{#                    <a class="page-link" href="?page={{ items.previous_page_number }}" aria-label="Previous">#}
{#                      <span aria-hidden="true">&laquo;</span>#}
{#                      <span class="sr-only">Previous</span>#}
{#                    </a>#}
{#                  </li>#}
{#                  {% endif %}#}
{##}
{#                  <li class="page-item active">#}
{#                    <a class="page-link" href="?page={{ items.number }}">{{ items.number }}#}
{#                      <span class="sr-only">(current)</span>#}
{#                    </a>#}
{#                  </li>#}
{##}
{#                  {% if items.has_next %}#}
{#                  <li class="page-item">#}
{#                    <a class="page-link" href="?page={{ items.next_page_number }}" aria-label="Next">#}
{#                      <span aria-hidden="true">&raquo;</span>#}
{#                      <span class="sr-only">Next</span>#}
{#                    </a>#}
{#                  </li>#}
{#                  {% endif %}#}
{#                </ul>#}
{#              </nav>#}
{#              {% endif %}#}
            <div class="row" data-aos="fade-up">
              <div class="col-md-12 text-center">
                <div class="site-block-27">
                  <ul>
                    {% if items.has_previous %}
                      <li><a href="?page={{ items.previous_page_number }}{% if articul %}&articul={{ articul }}{% endif %}{% if min_price %}&min_price={{ min_price }}{% endif %}{% if max_price %}&max_price={{ max_price }}{% endif %}" class="previous">&lt;<</a></li>
                    {% endif %}
                    {% for link in pagination_links %}
                      <li><a href="?{{ link.query_parameters }}">{{ link.page_number }}</a></li>
                    {% endfor %}
                    {% if items.has_next %}
                      <li><a href="?page={{ items.next_page_number }}{% if articul %}&articul={{ articul }}{% endif %}{% if min_price %}&min_price={{ min_price }}{% endif %}{% if max_price %}&max_price={{ max_price }}{% endif %}" class="next">>&gt;</a></li>
                    {% endif %}
{#                  {% if items.has_previous %}#}
{#                    <li><a href="?page={{ items.previous_page_number }}">&lt;</a></li>#}
{#                  {% endif %}#}
{#                      {% for i in pages %}#}
{#                          <li {% if items.number == i %}class="active"{% endif %}><a href="?page={{ i }}?{{ link.query_parameters }}"><span>{{ i }}</span></a></li>#}
{#                      {% endfor %}#}
{#                  {% if items.has_next %}#}
{#                    <li><a href="?page={{ items.next_page_number }}">&gt;</a></li>#}
{#                  {% endif %}#}
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-3 order-1 mb-5 mb-md-0">
            <div class="border p-4 rounded mb-4">
              <h2 class="mb-3 h6 text-black d-block">Категории</h2>
              {% if category != 'all' %}
              <ul class="list-unstyled mb-0">
                  {% for sub in category.subcategories.all %}
                      {%  if sub.title == subcategory.title %}
                  <li class="mb-1"><a href="{% url 'core:shop' category.title sub.title %}" class="d-flex"><span>{{ sub.title }}</span></a></li>
                      {% else %}
                  <li class="mb-1"><a href="{% url 'core:shop' category.title sub.title %}" class="d-flex text-dark"><p>{{ sub.title }}</p></a></li>
                      {% endif %}
                  {% endfor %}
              </ul>
              {% else %}
            <ul class="list-unstyled mb-0">
                  {% for sub in categories %}
                <li class="mb-1"><a href="{% url 'core:shop' sub.title 'all'%}" class="d-flex"><span>{{ sub.title }}</span> <span class="text-black ml-auto"></span></a></li>
                  {% endfor %}
              </ul>
            {% endif %}
            </div>
<form method="get">
            <div class="border p-4 rounded mb-4">
                <div class="box">
  <h3 class="mb-3 h6 text-black d-block">Цена</h3>
                    <div class="price-input">
        <div class="field">
            <div style="display:flex;">
          <span>от:</span>
          <input type="number" style="border: none; width: 78px" class="input-min" value="0">
            </div>
            <div style="display:flex;">
            <span>до:</span>
          <input type="number" style="border: none; width: 78px;" class="input-max" value="1000000">
            </div>
        </div>
        <div class="field">

        </div>
      </div>
      <div class="slider">
        <div class="progress"></div>
      </div>
      <div class="range-input">
        <input type="range" class="range-min" min="0" name="min_price" max="990000" value="0" step="1000">
        <input type="range" class="range-max" min="0" name="max_price" max="1000000" value="1000000" step="1000">
      </div>
{#    <div class="values">#}
{#        <div>₸<span id="first"></span></div> - <div>₸<span id="second"></span></div>#}
{#    </div>#}
{##}
{#    <div class="slider" data-value-0="#first" data-value-1="#second" data-range="#third"></div>#}

</div>

              </div>
                </form>
            </div>
          </div>
        </div>

      </div>
    </div>
    {% include  'footer.html' %}
  </div>

  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js'%}"></script>
  <script src="{% static 'js/popper.min.js'%}"></script>
  <script src="{% static 'js/bootstrap.min.js'%}"></script>
  <script src="{% static 'js/owl.carousel.min.js'%}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
  <script src="{% static 'js/aos.js'%}"></script>
  <script src="{% static 'js/main.js'%}"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.css">
{#  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.js"></script>#}
  <script src="https://cdpn.io/cpe/boomboom/pen.js?key=pen.js-2219196b-3514-a640-a3ea-997fd6b302a0" crossorigin=""></script>
  <script>
      const rangeInput = document.querySelectorAll(".range-input input"),
priceInput = document.querySelectorAll(".price-input input"),
range = document.querySelector(".slider .progress");
let priceGap = 1000;

priceInput.forEach(input =>{
    input.addEventListener("input", e =>{
        let minPrice = parseInt(priceInput[0].value),
        maxPrice = parseInt(priceInput[1].value);

        if((maxPrice - minPrice >= priceGap) && maxPrice <= rangeInput[1].max){
            if(e.target.className === "input-min"){
                rangeInput[0].value = minPrice;
                range.style.left = ((minPrice / rangeInput[0].max) * 100) + "%";
            }else{
                rangeInput[1].value = maxPrice;
                range.style.right = 100 - (maxPrice / rangeInput[1].max) * 100 + "%";
            }
        }
    });
});

rangeInput.forEach(input =>{
    input.addEventListener("input", e =>{
        let minVal = parseInt(rangeInput[0].value),
        maxVal = parseInt(rangeInput[1].value);

        if((maxVal - minVal) < priceGap){
            if(e.target.className === "range-min"){
                rangeInput[0].value = maxVal - priceGap
            }else{
                rangeInput[1].value = minVal + priceGap;
            }
        }else{
            priceInput[0].value = minVal;
            priceInput[1].value = maxVal;
            range.style.left = ((minVal / rangeInput[0].max) * 100) + "%";
            range.style.right = 100 - (maxVal / rangeInput[1].max) * 100 + "%";
        }
    });
});
  </script>
  </body>
    <script type="text/javascript">
    const buttons = document.querySelectorAll('button[id="add_to_card"]');
    console.log(buttons)
    for(let i = 0; i < buttons.length ; i++) {
        if(buttons[i].id == 'add_to_card'){
            console.log(buttons[i]['value'])
            buttons[i].addEventListener('click',function(e){
                e.preventDefault();
                $.ajax({
                    type:'POST',
                    url:'{% url "core:add-to-cart1" %}',
                    data:
                    {
                        slug:buttons[i]['value'],
                        csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                    },
                    dataType:'json',
                    success:function(){
                        let p = document.getElementById('number');
                        console.log(p)
                        alert("Добавлено в корзину " + buttons[i]['name']);
                    }
                })
            });
        }
    }
</script>
</html>